name: Build
# 自动化生成测试报告，测试项目是否可以构建成功，执行所有单元测试，lint报告
# push到main触发，build分支通过标识触发
on:
  push:
    branches:
      - build

# 确保同一并发组中只有一个工作流实例在运行
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_and_apk:
    name: "Local tests and APKs"
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    timeout-minutes: 60

    steps:
      # 下载代码
      - name: Checkout
        uses: actions/checkout@v4

      # 配置jdk
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      # 配置gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      # 执行一次构建，检查是否成功，出现异常不执行后面操作
      - name: Build debug apk
        continue-on-error: false
        run: ./gradlew assembleDebug

      # 生成lint报告
      - name: Check lint
        run: ./gradlew lint
      # 上传lint报告
      - name: Upload lint reports (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: '**/build/reports/lint-results-*.html'

      # 生成内部单元测试报告
      - name: Check test
        continue-on-error: true
        run: ./gradlew test
      # 上传test报告
      - name: Upload test reports (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: '**/build/reports/tests/test*UnitTest'