name: Debug Apk
# 打正式包 apk，提交蒲公英
# tags触发
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 配置jdk
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      # 配置gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      # baseline基线配置文件生成环境
      - name: Install GMD image for baseline profile generation
        run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager "system-images;android-33;aosp_atd;x86_64"

      - name: Accept Android licenses
        run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Build with Gradle
        run: ./gradlew :app:assembleRelease

      # 正式包签名
      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          # override default build-tools version (33.0.0) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload File to Pgyer
        uses: PGYER/pgyer-upload-app-action@v1.3
        with:
          _api_key: ${{ secrets.PGYER_API_TOKEN }}
          appFilePath: ${{steps.sign_app.outputs.signedReleaseFile}}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
